export const SOCKET_CHANNEL = {
  NOTIFICATION: 'NOTIFICATION',
  FRIEND: 'FRIEND',
  MESSAGE: 'MESSAGE'
}

export const NOTIFICATION_TYPE = {
  RECEIVE_NOTIFICATION: 'RECEIVE_NOTIFICATION'
}

export const FRIEND_TYPE = {
  INIT: 'INIT',
  GET_ONLINE_FRIEND_LIST: 'GET_ONLINE_FRIEND_LIST',
  HAS_NEW_ONLINE_USER: 'HAS_NEW_ONLINE_USER',
  HAS_NEW_OFFLINE_USER: 'HAS_NEW_OFFLINE_USER'
}

export const MESSAGE_TYPE = {
  SEND_MESSAGE: 'SEND_MESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE'
}
