export const SOCKET_CHANNEL = {
  NOTIFICATION: 'NOTIFICATION',
  FRIEND: 'FRIEND',
  MESSAGE: 'MESSAGE'
}

export const NOTIFICATION_TYPE = {
  HAS_NEW_NOTIFICATION: 'HAS_NEW_NOTIFICATION'
}

export const FRIEND_TYPE = {
  INIT: 'INIT',
  GET_ONLINE_FRIEND_LIST: 'GET_ONLINE_FRIEND_LIST',
  HAS_NEW_ONLINE_USER: 'HAS_NEW_ONLINE_USER',
  HAS_NEW_OFFLINE_USER: 'HAS_NEW_OFFLINE_USER'
}

export const MESSAGE_TYPE = {
  NEW_MESSAGE: 'NEW_MESSAGE'
}
